### ISSUE TITLE
Duplicates the :queue module

### ISSUE THREAD

**Issue by lpil** [princemaple/elixir-queue#1]
Hiya 

Seems like this library does the same thing as the :queue module in the standard library. Perhaps you could utilise it and make this library a wrapper? 

Cheers, 
Louis

**Comment by princemaple** [comment]
Hi @lpil 

I don't know how you found this new package so quickly :)
"A primitive queue data structure that doesn't spawn a separate process"
This is the purpose.

Thanks,
Po

**Comment by princemaple** [comment]
Haha, somehow I thought erlang :queue spawns a new process.

**Comment by princemaple** [comment]
Played too much with :ets I guess.

I'll update with `:queue`

**Comment by princemaple** [comment]
Thanks!

**Comment by princemaple** [comment]
Ok @lpil now it's a wrapper of `:queue` and it has `Inspect`, `Collectable` and `Enumerable` implemented :)

**Comment by lpil** [comment]
Nice. Might I suggest having inspect conform to the convention of having data without a literal syntax start with a #?

When I wrap it I use `#MyProject.Queue<[1, 2, 3]>`

Also might be good to use the word queue so people don't need to look up what Qex means when they discover the data structure in a codebase.

**Comment by princemaple** [comment]
@lpil I wanted to name this package just `Queue`, but it's taken. :(
Fixed the inspect implementation, another thing I remembered wrong.
