### ISSUE TITLE
Weird error when using pipe

### ISSUE THREAD

**Issue by pfspontus** [princemaple/elixir-queue#4]
iex(3)> q = Qex.new                        
#Qex<[]>
iex(4)> q = q |> Qex.push(1)        
** (SyntaxError) iex:4: unexpected token: " " (column 6, codepoint U+00A0)

iex(4)> q = Qex.push(q, 1)  
#Qex<[1]>
iex(5)>

**Comment by princemaple** [comment]
Did you copy it from somewhere else? 0x00A0 is not a valid character.

**Comment by pfspontus** [comment]
I'm truly sorry, yesterday I could replicate this over and over again. Now it's not showing all is working correctly.

**Comment by princemaple** [comment]
That's weird... Anyhow, no need to be sorry! 😄
